name: "Deploy"

on: 
  workflow_run:
    workflows: ["Build and push packages"]
    branches: 
      - "master"
      - "*.*.*"
    types: 
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SEMVER_REGEX: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$



jobs:
  stop:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'
    
    steps:
      - name: Stop
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop $(docker ps -f name=platform-explorer-indexer -q)
            docker stop $(docker ps -f name=platform-explorer-api -q)
            docker rm platform-explorer-api platform-explorer-indexer

  drop_db:
      runs-on: ubuntu-latest

      needs: stop
      
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      

      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.workflow_run.head_branch }} =~ ${{env.SEMVER_REGEX}}]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi

      - name: DEBUG
        run: echo "Works. Tag is ${{github.event.workflow_run.head_branch}}"

      - name: DEBUG#1
        run: echo ${{steps.check-tag.outputs.match}}

      - name: DEBUG#2
        run: echo ${{startsWith(github.event.workflow_run.head_branch, env.SEMVER_REGEX)}}

      - name: Drop database
        if: ${{startsWith(github.event.workflow_run.head_branch,'*.*.*')}}
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            git -C ./platform-explorer pull
            docker pull owl352/refinery_cli_docker
            
            docker run --rm --env-file api.env ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api npm run db:drop
            docker run --rm --env-file api.env ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:indexer refinery migrate -e DATABASE_URL -p /app/migrations

  start:
    runs-on: ubuntu-latest

    needs: drop_db
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to the server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            git -C ./platform-explorer pull
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:indexer
            docker run -d -p 3005:3005 --restart always --env-file api.env --name platform-explorer-api ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api
            sleep 3
            docker run -d --env-file api.env --restart always --name platform-explorer-indexer ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:indexer cargo run