name: Release

on:
  workflow_run:
    workflows: ["Build and push packages"]
    branches: [v*]
    types: 
      - completed

jobs: 
  create_tag:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'
    steps:

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create a GitHub release
      uses: release-drafter/release-drafter@v6
      with:
        version: ${{steps.tag.outputs.tag}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}